version: '3'
services: 
    app:
        container_name: Webbanhang
        restart: always
        build: .
        ports:
            - '80:3000'
        links:
            - mongo
        environment:
            - JWT_KEY=secret
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'